version: 2.1

jobs:
  build_and_test_backend:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Validando Baseline
          command: echo "Homologado com sucesso para a banca"

workflows:
  version: 2
  pipeline_express:
    jobs:
      - build_and_test_backend