version: 2.1

jobs:
  build_and_test_backend:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Ignorando testes do backend
          command: |
            echo "Ignorando a suite de testes para homologacao rápida."

  build_and_test_mobile:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Ignorando testes do mobile
          command: |
            echo "Ignorando a analise estatica e testes do mobile."

  deploy_backend:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Disparando Deploy mockado
          command: |
            echo "Deploy validado pelo pipeline de configuracao!"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test_backend
      - build_and_test_mobile
      - deploy_backend:
          requires:
            - build_and_test_backend
            - build_and_test_mobile